language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: w8zING36brlSozA5VyqP5krbb2DAm0hYFXyriASuYb1jqhWZqBjsJMfm2DAr+ybaZHayB4kA5VBxLraHyBqad4qxeOh3DfMTQWo/qb6XTkIOowFO9Ru3NCXOA9UAJzTVDlMW2cJEus93nrQZNCxg0E65i/2PM6CgdspPD5JSwSjtCIW9wUHwcOvV9ScpZM4CV7HVUXTyNGEBiGYKGmVkbWL7i/+pwRzW6pOSBPglLLGaX/PTRuBKG3lFV0DQu+59b5AG+ZbALHrc9OlyM/TFDtBkyuN5O+/L11UVJl7gEJKfSSbJob+f26hQaMAIyW8jIhQSWCjhteYgluEyNaitUYhZ1YRqIy5uFC7yXHFaQi/+aGN/2yUJzUi3rzX95vq3URMAX6Pvfv7f+pBYsa6BWZtsJ7pKi47evyFJ6M2tcnVY0qmax9/IM2l0ZB1yrqApSx2pDUdX3CZIyKJRt3LKoJPOSdA+IFqgLPOK8Hc0g2c2sdfImTlr8JdIw5yVP5atAfMn1xGtehlSPnbs5QTfjm3qtF3bFPC95R9jL3AUnaZposYMWdJa0hEU6e+Yn3n4GLweWAQf5jw73dOhMUTCNoUt/K0fl6yz7epLg2G3/wx7Jx5cxB/GYrcs3Bcoo9FFBlPOUPX9f5umipxVzvTaFU5plnLBSv7gksn+jKXR+CM=
    on:
      branch: master
      tags: true